version: '3'

services:
  backend:
    container_name: wsa-backend
    build:
      context: ./backend
    ports:
    - "3002:3002"



  frontend:
    container_name: wsa-frontend
    build:
      context: ./frontend
    ports:
    - "5173:80"